name: 'crypto_analytics'
version: '1.0.0'
config-version: 2

profile: 'crypto_analytics'

model-paths: ['models']
seed-paths: ['seeds']

models:
  crypto_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
