crypto_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: warehouse
      password: warehouse
      port: 5432
      dbname: warehouse
      schema: public
      threads: 2
